### ISSUE TITLE
Add support for deleted annotations

### ISSUE THREAD

**Issue by damien-king** [solean/ibooks-highlights#2]
Hi! 

Thanks for making this, it's super helpful :). I would create a PR but no permissions. 

Hoping to add:

`zannotationdeleted` to `const ANNOTATIONS_QUERY` in constants.js 

and something to the effect of 

```
    var annotation = {
      ...,
      deleted: rawAnnData.ZANNOTATIONDELETED === 1 ? true: false
    };
```

So I can filter out deleted annotations when I'm querying. 

Thanks!

**Comment by solean** [comment]
Hey. I think you should be able to submit a PR if you fork the repo and create a new branch. If not, I can make the change but you should get the commit credit since it was your idea lol.

**Comment by solean** [comment]
Added in commit: [d63131](https://github.com/solean/ibooks-highlights/commit/d631315f85a24924a2c82f154569861e61c074b4)
