### ISSUE TITLE
Bug: Deleted highlights are not showing deleted

### ISSUE THREAD

**Issue by Yadav106** [solean/ibooks-highlights#8]
<img width="441" alt="Screenshot 2024-09-22 at 10 59 19 AM" src="https://github.com/user-attachments/assets/deb725c1-e77b-4ce3-8307-3ec8b0c2518c">

```js
{
    representativeText: 'Viewing as he did for intuitive feel—for trend and generality—every step in the course of human/robot interaction seemed to depend on dependence. ',
    selectedText: 'generality',
    createdOn: '2024-09-22 05:25:23',
    updatedOn: '2024-09-22 05:26:34',
    note: null,
    chapter: null,
    bookId: 'book-id-hidden',
    deleted: false,
    book: {
      title: 'The Robots of Dawn',
      author: 'Isaac Asimov',
      filePath: 'location-hidden'
    }
}
```
The highlight on 'generality' was first added then removed, but the code still shows the value of deleted as false

**Comment by Yadav106** [comment]
The solution:
in the constants.js file, the query for getting data from the sqlite database is not updated

```sql
const ANNOTATIONS_QUERY = 'SELECT zannotationassetid, zannotationrepresentativetext, zannotationselectedtext, datetime(zannotationcreationdate + strftime("%s", "2001-01-01"), "unixepoch") as CREATED_ON, datetime(zannotationmodificationdate + strftime("%s", "2001-01-01"), "unixepoch") as UPDATED_ON, zannotationnote, zfutureproofing5,zannotationdeleted FROM zaeannotation ORDER BY created_on DESC';
```

this query includes zannotationdeleted column which fixes the bug
can i create a pr for this?

**Comment by solean** [comment]
Sorry for not getting back to you until now, I've been away on vacation. Feel free to create a pr for this. Thanks Sahil!

**Comment by Yadav106** [comment]
Thanks! Will do!

**Comment by Yadav106** [comment]
I've opened a PR!

**Comment by solean** [comment]
Merged the pr. Thanks for catching this and fixing it!
